-- Créer la base uniquement si inexistante
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TP1_Franck')
BEGIN
	CREATE DATABASE TP1_Franck;
END

GO

USE TP1_Franck;
GO

-- Créer la table DEPT si inexistante
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'DEPT' AND xtype = 'U')
BEGIN
	CREATE TABLE DEPT
	(DEPTNO TINYINT NOT NULL,
	DNAME NVARCHAR(50) NOT NULL,
	LOC NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)
	)
END


-- Créer la table EMP si inexistante
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'EMP' AND xtype = 'U')
BEGIN
	CREATE TABLE EMP
	(EMPNO SMALLINT NOT NULL,
	ENAME NVARCHAR(50) NOT NULL,
	JOB NVARCHAR(50) NOT NULL,
	HIREDATE DATE NOT NULL,
	SAL MONEY NOT NULL,
	COMM MONEY,
	MGR SMALLINT,
	DEPTNO TINYINT NOT NULL,
	CONSTRAINT PK_EMP PRIMARY KEY (EMPNO),
	CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
	CONSTRAINT FK_EMP_MGR FOREIGN KEY (MGR) REFERENCES EMP (EMPNO)
	);
END